### ISSUE TITLE
There seems to be a problem with the version ^0.2.26 and typescript

### ISSUE THREAD

**Issue by wanliyunyan** [jjordy/swr-devtools#1]
![image](https://user-images.githubusercontent.com/10751248/78316780-14edea00-7593-11ea-8b1d-044dc7057f00.png)

TS2322: Type '{ children: Element; cache: Cache; mutate: mutateInterface<any>; }' is not assignable to type 'IntrinsicAttributes & SWRDevtoolsProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & SWRDevtoolsProps'.

"@jjordy/swr-devtools": "^0.2.26"
"typescript": "^3.8.3",

What evidence do you need, I will provide you，thanks for the plugin

**Comment by jjordy** [comment]
Hey man sorry i'm making massive changes and have been struggling with getting the layout to work the way i want. In the latest version you no longer need to wrap it around your app that is the only issue your experiencing i believe but to be honest i've been pushing new versions to npm testing on my production applications because i thought no one was using except me hehe.. I will get these issues fixed tomorrow and hopefully there will be some more consistency after that. Let me know if you have any other issues. Like I said i struggling with getting the layout to work like i want when using react-rnd so its still a total work in progress. Heres an example of how it should work right now.

```jsx
<>
<SWRDevtools mutate={mutate} cache={cache} />
<App />
</>

**Comment by jjordy** [comment]
I've updated the documentation on how to implement the component and made some significant changes to the way the component functions. So I'm going to close this issue please let me know if you have any more issues with implementing and ill be happy to reopen the issue.
