### ISSUE TITLE
Can I fork this repository and take over the development?

### ISSUE THREAD

**Issue by k3nt0w** [jjordy/swr-devtools#12]
Hi jjordy, I'm Kento Watanabe（ @k3nt0w ）
I couldn't find any Email contact information, so I contacted you via Issue. 

I usually use SWR for my development, but I felt it was difficult to manage states in SWR. I looked for an easy-to-use development tool, and found this library. This library is very easy to use and I feel it should be used more often! 

However, this package does not seem to be maintained, so I am planning to fork it and develop it myself for various updates. I've checked the MIT license, but is it okay to fork and develop it and publish it? I have already published it from my repository, but I will remove it if there is a problem.

**Comment by jjordy** [comment]
Absolutely have fun there is a lot that can be done to make it more like redux dev tools! Sent from Mail for Windows 10 From: Kento WatanabeSent: Monday, April 26, 2021 4:10 AMTo: jjordy/swr-devtoolsCc: SubscribedSubject: [jjordy/swr-devtools] Can I fork this repository and take over the development? (#12) Hi jjordy, I'm Kento Watanabe（ @k3nt0w ）I couldn't find any Email contact information, so I contacted them via Issue.I usually use SWR for my development, but I felt it was difficult to manage states in SWR. I looked for an easy-to-use development tool, and found this library, which I found to be very nice! However, this package does not seem to be maintained, so I am planning to fork it and develop it myself for various updates.I've checked the MIT license, but is it okay to fork and develop it and publish it? I have already published it from my repository, but I will remove it if there is a problem.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jjordy** [comment]
I have updated all the packages and done a few upgrades I do have a few more upgrades planned but feel free to fork it and do whatever you want I am going to close this issue out thanks!

**Comment by k3nt0w** [comment]
@jjordy 
 Thanks for the quick reply! Also, thank you so much for forking and allowing me to develop!

I will be working on the forked repository with my team.
However, if the development of this repository becomes active, I wanna contribute to the development of this one as well.

Thank you!
